=== yuvraj108c/mo-blog-2/server/data/xsd/users.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="user">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string" />
                <xs:element name="email" type="xs:string" />
                <xs:element name="password" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" />
        </xs:complexType>
    </xs:element>

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="user" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== yuvraj108c/mo-blog-2/server/data/users.xml
<?xml version="1.0" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/users.xsd">
    <user id="1">
        <username>John</username>
        <email>john@gmail.com</email>
        <password>827CCB0EEA8A706C4C34A16891F84E7B</password>
    </user>
    <user id="2">
        <username>Sam</username>
        <email>sam@gmail.com</email>
        <password>202cb962ac59075b964b07152d234b70</password>
    </user>
    <user id="3">
        <username>User a</username>
        <email>a@gmail.com</email>
        <password>827ccb0eea8a706c4c34a16891f84e7b</password>
    </user>
    <user id="4">
        <username>Johnf</username>
        <email>johnf@gmail.com</email>
        <password>827ccb0eea8a706c4c34a16891f84e7b</password>
    </user>
    <user id="5">
        <username>Johnff</username>
        <email>johnff@gmail.com</email>
        <password>827ccb0eea8a706c4c34a16891f84e7b</password>
    </user>
    <user id="6">
        <username>johntest</username>
        <email>johntest@gmail.com</email>
        <password>098f6bcd4621d373cade4e832627b4f6</password>
    </user>
    <user id="7">
        <username>john12</username>
        <email>john@gmail.com12</email>
        <password>c20ad4d76fe97759aa27a0c99bff6710</password>
    </user>
    <user id="8">
        <username>johntt</username>
        <email>john@gmail.comtt</email>
        <password>098f6bcd4621d373cade4e832627b4f6</password>
    </user>
</users>
